server:
  port: 9090
file:
  input: 
chefs:
  url: https://submit.digital.gov.bc.ca/app/api/v1/
  forms:
    clinicRecords:
      formId: 
      apiKey: 
    haHierarchy:
      formId: 
      apiKey: 
    reportingDates:
      formId: 
      apiKey: 
user:
  token: 